### ISSUE TITLE
link compile error

### ISSUE THREAD

**Issue by denegny** [Twins-Divyanshu-Sharma/Hex#7]
**Try**

`make`

### output

```
g++ -o binary/Hex build/BloomRenderer.o build/Config.o build/Engine.o build/FBO.o build/FontAtlas.o build/FontRenderer.o build/HexagonRenderer.o build/Hexagons.o build/IconRenderer.o build/Mesh.o build/ScreenQuadRenderer.o build/ShaderProgram.o build/Texture.o build/Win.o build/main.o -lGL -lglfw -lX11 -lXxf86vm -lXrandr -lpthread -ldl -lXinerama -lXcursor
/usr/bin/ld: невозможно найти -lXxf86vm: Нет такого файла или каталога
collect2: error: ld returned 1 exit status
make: *** [makefile:27: Hex] Ошибка 1
```
![изображение](https://github.com/Twins-Divyanshu-Sharma/Hex/assets/3710958/9e6c5e4b-a092-4c44-be67-970d1dd79481)

**Comment by Twins-Divyanshu-Sharma** [comment]
This issue can be resolved in two ways:
1> Install the library: libXxf86vm or libXxf86vm-dev in your system
     `  sudo apt-get update && sudo apt-get install libxxf86vm-dev  `
2> Or remove the library dependency in the makefile. To do so, open makefile in the repo. Then goto line 13 which is like this:
lib =-lGL -lglfw -lX11 -lXxf86vm -lXrandr -lpthread -ldl -lXinerama -lXcursor
change it to remove -lXxf86vm, like this:
lib =-lGL -lglfw -lX11  -lXrandr -lpthread -ldl -lXinerama -lXcursor

then run make, sudo make install
